[tool.poetry]
name = "poetry-goodstart"
version = "0.1.0"
description = ""
authors = ["Anton Braun <merkme@yandex.ru>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
django = "^5.0.4"
python-telegram-bot = "^21.1.1"
poetry-plugin-export = "^1.7.1"

[tool.poetry.dev-dependencies]
pre-commit = "^3.7.0"
ruff = "^0.4.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
