target-version = "py312"
ignore = ["D100", "D104", "D105", "D106", "D203", "D212", "PLR0206", "D205"]
extend-exclude = [".venv", "migrations/", "*settings.py", "settings*.py", "env"]
line-length = 79
indent-width = 4
output-format = "grouped"

[lint]
select = ["E", "F", "B", "W", "I", "D", "PL"]

[format]
quote-style = "single"
indent-style = "tab"
docstring-code-format = true

[lint.per-file-ignores]
"__init__.py" = ["F401"]
"settings*" = ["E501", "F405"]
