# Generated by Django 5.0.4 on 2024-05-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudyClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_class_name', models.CharField(max_length=64, unique=True, verbose_name='Название учебного класса')),
                ('study_class_number', models.PositiveIntegerField(verbose_name='Номер учебного класса')),
            ],
            options={
                'verbose_name': 'Название учебного класса',
                'verbose_name_plural': 'Названия учебных классов',
            },
        ),
    ]
