# Generated by Django 5.0.4 on 2024-08-16 19:10

import django.db.models.deletion
import phonenumber_field.modelfields
import schooling.validators.phone_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudyClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_class_name', models.CharField(max_length=64, unique=True, verbose_name='Название учебного класса')),
                ('study_class_number', models.PositiveIntegerField(verbose_name='Номер учебного класса')),
            ],
            options={
                'verbose_name': 'учебный класс',
                'verbose_name_plural': 'Учебные классы',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Название предмета')),
                ('subject_key', models.CharField(blank=True, max_length=128, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'название предмета',
                'verbose_name_plural': 'Названия предметов',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('surname', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(help_text='Формат +7XXXXXXXXXX', max_length=128, region=None, validators=[schooling.validators.phone_validators.validate_phone_number], verbose_name='Номер телефона')),
                ('last_login_date', models.DateField(auto_now=True, verbose_name='Последнее посещение')),
                ('registration_date', models.DateField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('state', models.CharField(choices=[('start', 'Start'), ('help', 'Help'), ('schedule', 'Schedule'), ('feedback', 'Feedback'), ('feedback_subject_msg', 'Feedback Subject'), ('feedback_body_msg', 'Feedback Body'), ('left_lessons', 'Left Lessons')], default='start', max_length=50, verbose_name='Состояние пользователя')),
                ('paid_lessons', models.PositiveIntegerField(default=0, verbose_name='Оплаченые занятия')),
                ('parents_contacts', models.CharField(max_length=256, verbose_name='Контакты представителей')),
                ('study_class_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='schooling.studyclass', verbose_name='ID учебного класса')),
                ('subjects', models.ManyToManyField(to='schooling.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('surname', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(help_text='Формат +7XXXXXXXXXX', max_length=128, region=None, validators=[schooling.validators.phone_validators.validate_phone_number], verbose_name='Номер телефона')),
                ('last_login_date', models.DateField(auto_now=True, verbose_name='Последнее посещение')),
                ('registration_date', models.DateField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('state', models.CharField(choices=[('start', 'Start'), ('help', 'Help'), ('schedule', 'Schedule'), ('feedback', 'Feedback'), ('feedback_subject_msg', 'Feedback Subject'), ('feedback_body_msg', 'Feedback Body'), ('left_lessons', 'Left Lessons')], default='start', max_length=50, verbose_name='Состояние пользователя')),
                ('competence', models.ManyToManyField(to='schooling.subject', verbose_name='Предмет')),
                ('study_classes', models.ManyToManyField(to='schooling.studyclass', verbose_name='Учебный класс')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название занятия')),
                ('datetime_start', models.DateTimeField(verbose_name='Время начала занятия')),
                ('duration', models.PositiveIntegerField(default=45, help_text='Продолжительность занятия в минутах.', verbose_name='Продолжительность занятия')),
                ('is_passed', models.BooleanField(default=False, verbose_name='Занятие прошло')),
                ('is_passed_teacher', models.BooleanField(default=False, verbose_name='Занятие подтверждено учителем')),
                ('is_passed_student', models.BooleanField(default=False, verbose_name='Занятие подтверждено учеником')),
                ('test_lesson', models.BooleanField(default=False, verbose_name='Пробное занятие')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='schooling.student', verbose_name='Студент')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='schooling.subject', verbose_name='Предмет')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='schooling.teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'занятие',
                'verbose_name_plural': 'Занятия',
            },
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('name', 'subject', 'teacher_id', 'student_id', 'datetime_start', 'duration'), name='unique_lesson'),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('name', 'datetime_start')},
        ),
    ]
