# Generated by Django 5.0.4 on 2024-05-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Название предмета')),
                ('subject_key', models.CharField(blank=True, max_length=128, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Название предмета',
                'verbose_name_plural': 'Названия предметов',
            },
        ),
    ]
