# Generated by Django 5.0.4 on 2024-05-13 10:17

from django.db import migrations


def create_study_class_first(apps, schema_editor):
    """Create study class 'Первый класс'."""
    Subject = apps.get_model('schooling', 'StudyClass')
    Subject.objects.create(
        study_class_name='Первый класс',
        study_class_number=1
    )


def remove_study_class_first(apps, schema_editor):
    """Remove study class 'Первый класс' instance."""
    Subject = apps.get_model('schooling', 'StudyClass')
    remove_subject = Subject.objects.get(
        study_class_name='Первый класс',
    )
    remove_subject.delete()


def create_study_class_second(apps, schema_editor):
    """Create study class 'Второй класс'."""
    Subject = apps.get_model('schooling', 'StudyClass')
    Subject.objects.create(
        study_class_name='Второй класс',
        study_class_number=2
    )


def remove_study_class_second(apps, schema_editor):
    """Remove study class 'Второй класс' instance."""
    Subject = apps.get_model('schooling', 'StudyClass')
    remove_subject = Subject.objects.get(
        study_class_name='Второй класс',
    )
    remove_subject.delete()


def create_study_class_third(apps, schema_editor):
    """Create study class 'Третий класс'."""
    Subject = apps.get_model('schooling', 'StudyClass')
    Subject.objects.create(
        study_class_name='Третий класс',
        study_class_number=3
    )


def remove_study_class_third(apps, schema_editor):
    """Remove study class 'Третий класс' instance."""
    Subject = apps.get_model('schooling', 'StudyClass')
    remove_subject = Subject.objects.get(
        study_class_name='Третий класс',
    )
    remove_subject.delete()

def create_study_class_fourth(apps, schema_editor):
    """Create study class 'Четвертый класс'."""
    Subject = apps.get_model('schooling', 'StudyClass')
    Subject.objects.create(
        study_class_name='Четвертый класс',
        study_class_number=4
    )


def remove_study_class_fourth(apps, schema_editor):
    """Remove study class 'Четвертый класс' instance."""
    Subject = apps.get_model('schooling', 'StudyClass')
    remove_subject = Subject.objects.get(
        study_class_name='Четвертый класс',
    )
    remove_subject.delete()


def create_study_class_fifth(apps, schema_editor):
    """Create study class 'Пятый класс'."""
    Subject = apps.get_model('schooling', 'StudyClass')
    Subject.objects.create(
        study_class_name='Пятый класс',
        study_class_number=5
    )


def remove_study_class_fifth(apps, schema_editor):
    """Remove study class 'Пятый класс' instance."""
    Subject = apps.get_model('schooling', 'StudyClass')
    remove_subject = Subject.objects.get(
        study_class_name='Пятый класс',
    )
    remove_subject.delete()


def create_study_class_sixth(apps, schema_editor):
    """Create study class 'Шестой класс'."""
    Subject = apps.get_model('schooling', 'StudyClass')
    Subject.objects.create(
        study_class_name='Шестой класс',
        study_class_number=6
    )


def remove_study_class_sixth(apps, schema_editor):
    """Remove study class 'Шестой класс' instance."""
    Subject = apps.get_model('schooling', 'StudyClass')
    remove_subject = Subject.objects.get(
        study_class_name='Шестой класс',
    )
    remove_subject.delete()


def create_study_class_seventh(apps, schema_editor):
    """Create study class 'Седьмой класс'."""
    Subject = apps.get_model('schooling', 'StudyClass')
    Subject.objects.create(
        study_class_name='Седьмой класс',
        study_class_number=7
    )


def remove_study_class_seventh(apps, schema_editor):
    """Remove study class 'Седьмой класс' instance."""
    Subject = apps.get_model('schooling', 'StudyClass')
    remove_subject = Subject.objects.get(
        study_class_name='Седьмой класс',
    )
    remove_subject.delete()


def create_study_class_eighth(apps, schema_editor):
    """Create study class 'Восьмой класс'."""
    Subject = apps.get_model('schooling', 'StudyClass')
    Subject.objects.create(
        study_class_name='Восьмой класс',
        study_class_number=8
    )


def remove_study_class_eighth(apps, schema_editor):
    """Remove study class 'Восьмой класс' instance."""
    Subject = apps.get_model('schooling', 'StudyClass')
    remove_subject = Subject.objects.get(
        study_class_name='Восьмой класс',
    )
    remove_subject.delete()


def create_study_class_nineth(apps, schema_editor):
    """Create study class 'Девятый класс'."""
    Subject = apps.get_model('schooling', 'StudyClass')
    Subject.objects.create(
        study_class_name='Девятый класс',
        study_class_number=9
    )


def remove_study_class_nineth(apps, schema_editor):
    """Remove study class 'Девятый класс' instance."""
    Subject = apps.get_model('schooling', 'StudyClass')
    remove_subject = Subject.objects.get(
        study_class_name='Девятый класс',
    )
    remove_subject.delete()


def create_study_class_tenth(apps, schema_editor):
    """Create study class 'Десятый класс'."""
    Subject = apps.get_model('schooling', 'StudyClass')
    Subject.objects.create(
        study_class_name='Десятый класс',
        study_class_number=10
    )


def remove_study_class_tenth(apps, schema_editor):
    """Remove study class 'Десятый класс' instance."""
    Subject = apps.get_model('schooling', 'StudyClass')
    remove_subject = Subject.objects.get(
        study_class_name='Десятый класс',
    )
    remove_subject.delete()


def create_study_class_eleventh(apps, schema_editor):
    """Create study class 'Одиннадцатый класс'."""
    Subject = apps.get_model('schooling', 'StudyClass')
    Subject.objects.create(
        study_class_name='Одиннадцатый класс',
        study_class_number=11
    )


def remove_study_class_eleventh(apps, schema_editor):
    """Remove study class 'Одиннадцатый класс' instance."""
    Subject = apps.get_model('schooling', 'StudyClass')
    remove_subject = Subject.objects.get(
        study_class_name='Одиннадцатый класс',
    )
    remove_subject.delete()


class Migration(migrations.Migration):
    dependencies = [
        ('schooling', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            create_study_class_first, reverse_code=remove_study_class_first
        ),
        migrations.RunPython(
            create_study_class_second, reverse_code=remove_study_class_second
        ),
        migrations.RunPython(
            create_study_class_third, reverse_code=remove_study_class_third
        ),
        migrations.RunPython(
            create_study_class_fourth, reverse_code=remove_study_class_fourth
        ),
        migrations.RunPython(
            create_study_class_fifth, reverse_code=remove_study_class_fifth
        ),
        migrations.RunPython(
            create_study_class_sixth, reverse_code=remove_study_class_sixth
        ),
        migrations.RunPython(
            create_study_class_seventh, reverse_code=remove_study_class_seventh
        ),
        migrations.RunPython(
            create_study_class_eighth, reverse_code=remove_study_class_eighth
        ),
        migrations.RunPython(
            create_study_class_nineth, reverse_code=remove_study_class_nineth
        ),
        migrations.RunPython(
            create_study_class_tenth, reverse_code=remove_study_class_tenth
        ),
        migrations.RunPython(
            create_study_class_eleventh, reverse_code=remove_study_class_eleventh
        ),
    ]
