# Generated by Django 5.0.6 on 2024-05-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooling', '0003_add_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='telegram_id',
            field=models.BigIntegerField(unique=True, verbose_name='Telegram ID'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='telegram_id',
            field=models.BigIntegerField(unique=True, verbose_name='Telegram ID'),
        ),
    ]
