# Generated by Django 5.0.4 on 2024-09-17 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooling', '0003_add_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='homework_url',
            field=models.URLField(help_text='Там, где размещено домашнее задание', null=True, verbose_name='Ссылка на домашнее задание'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_meeting_url',
            field=models.URLField(help_text='Там, где будет проходить встреча', null=True, verbose_name='Ссылка на проведение урока'),
        ),
    ]
