# Generated by Django 5.0.6 on 2024-05-21 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooling', '0003_add_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название занятия')),
                ('datetime_start', models.DateTimeField(verbose_name='Время начала занятия')),
                ('datetime_end', models.DateTimeField(verbose_name='Время окончания занятия')),
                ('is_passed', models.BooleanField(default=False, verbose_name='Занятие прошло')),
                ('test_lesson', models.BooleanField(default=False, verbose_name='Тестовое занятие')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='schooling.student', verbose_name='ID студента')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='schooling.subject', verbose_name='Предмет')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='schooling.teacher', verbose_name='ID преподавателя')),
            ],
            options={
                'verbose_name': 'Занятие',
                'verbose_name_plural': 'Занятия',
            },
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('name', 'subject', 'teacher_id', 'student_id', 'datetime_start', 'datetime_end'), name='unique_lesson'),
        ),
    ]
