# Generated by Django 5.0.6 on 2024-06-04 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schooling', '0004_alter_student_paid_lessons_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studyclass',
            options={'verbose_name': 'Учебный класс', 'verbose_name_plural': 'Учебные классы'},
        ),
    ]
