# Generated by Django 5.0.6 on 2024-06-21 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooling', '0004_alter_student_study_class_id'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lesson',
            name='unique_lesson',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='datetime_end',
        ),
        migrations.AddField(
            model_name='lesson',
            name='duration',
            field=models.PositiveIntegerField(default=10, verbose_name='Продолжительность занятия'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('name', 'subject', 'teacher_id', 'student_id', 'datetime_start', 'duration'), name='unique_lesson'),
        ),
    ]
