# Generated by Django 5.0.4 on 2025-02-14 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooling', '0004_lesson_homework_url_lesson_video_meeting_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='is_passed_student',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='duration',
            field=models.PositiveIntegerField(default=60, help_text='Продолжительность занятия в минутах.', verbose_name='Продолжительность занятия'),
        ),
    ]
