# Generated by Django 5.0.4 on 2025-02-11 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schooling', '0004_lesson_homework_url_lesson_video_meeting_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='test_lesson',
        ),
    ]
