# Generated by Django 5.0.4 on 2025-02-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooling', '0004_lesson_homework_url_lesson_video_meeting_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='notification_sent',
            field=models.BooleanField(default=False, verbose_name='Уведомление отправлено'),
        ),
    ]
