# Generated by Django 5.0.6 on 2024-05-27 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooling', '0004_alter_student_telegram_id_alter_teacher_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='paid_lessons',
            field=models.PositiveIntegerField(default=0, verbose_name='Оплаченые занятия'),
        ),
    ]
