# Generated by Django 5.0.6 on 2024-06-07 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schooling', '0005_alter_studyclass_options'),
        ('schooling', '0005_alter_studyclass_options_student_state_teacher_state'),
    ]

    operations = [
    ]
