# Generated by Django 5.0.4 on 2025-02-15 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooling', '0005_lesson_lesson_count_lessongroup_lesson_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='regular_schedule',
            field=models.BooleanField(default=False, verbose_name='Регулярное расписание'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='duration',
            field=models.PositiveIntegerField(default=60, help_text='Продолжительность занятия в минутах.', verbose_name='Продолжительность занятия'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_count',
            field=models.PositiveIntegerField(default=1, help_text='Сколько занятий создать', verbose_name='Количество создаваемых занятий'),
        ),
    ]
