# Generated by Django 5.0.6 on 2024-05-27 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooling', '0005_alter_student_paid_lessons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='study_class_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='students', to='schooling.studyclass', verbose_name='ID учебного класса'),
        ),
    ]
