# Generated by Django 5.0.4 on 2025-02-12 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooling', '0005_lesson_notification_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='teacher_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='schooling.teacher', verbose_name='Преподаватель'),
        ),
    ]
