# Generated by Django 5.0.6 on 2024-06-26 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooling', '0005_remove_lesson_unique_lesson_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='duration',
            field=models.PositiveIntegerField(default=45, help_text='Продолжительность занятия в минутах.', verbose_name='Продолжительность занятия'),
        ),
    ]
