# Generated by Django 5.0.4 on 2025-02-16 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schooling', '0005_alter_student_options_alter_teacher_options_and_more'),
        ('schooling', '0005_lesson_lesson_count_lesson_regular_lesson_and_more'),
    ]

    operations = [
    ]
