# Generated by Django 5.0.4 on 2025-02-12 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schooling', '0006_alter_lesson_teacher_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='notification_sent',
        ),
    ]
