# Generated by Django 5.0.4 on 2025-02-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooling', '0006_lesson_regular_schedule_alter_lesson_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='regular_schedule',
        ),
        migrations.AddField(
            model_name='lesson',
            name='regular_lesson',
            field=models.BooleanField(default=False, verbose_name='Регулярное занятие'),
        ),
    ]
