# Generated by Django 5.0.6 on 2024-06-14 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooling', '0007_alter_lesson_options_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='state',
            field=models.CharField(choices=[('start', 'Start'), ('help', 'Help'), ('schedule', 'Schedule'), ('feedback', 'Feedback'), ('feedback_subject_msg', 'Feedback Subject'), ('feedback_body_msg', 'Feedback Body')], default='start', max_length=50, verbose_name='Состояние пользователя'),
        ),
        migrations.AlterField(
            model_name='student',
            name='study_class_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='schooling.studyclass', verbose_name='ID учебного класса'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='state',
            field=models.CharField(choices=[('start', 'Start'), ('help', 'Help'), ('schedule', 'Schedule'), ('feedback', 'Feedback'), ('feedback_subject_msg', 'Feedback Subject'), ('feedback_body_msg', 'Feedback Body')], default='start', max_length=50, verbose_name='Состояние пользователя'),
        ),
    ]
