# Generated by Django 5.0.4 on 2025-02-22 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooling', '0007_lesson_lesson_count_lesson_regular_lesson_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='homework_url',
        ),
        migrations.AddField(
            model_name='lesson',
            name='homework_text',
            field=models.TextField(blank=True, help_text='Описание домашнего задания', null=True, verbose_name='Текст домашнего задания'),
        ),
        migrations.CreateModel(
            name='HomeworkFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='lesson_homework/files/', verbose_name='Файл')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_files', to='schooling.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Файл для д/з',
                'verbose_name_plural': 'Файлы для д/з',
            },
        ),
        migrations.CreateModel(
            name='HomeworkImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='lesson_homework/images/', verbose_name='Изображение')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_images', to='schooling.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Изображение для д/з',
                'verbose_name_plural': 'Изображения для д/з',
            },
        ),
    ]
