# Generated by Django 5.0.6 on 2024-06-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooling', '0007_alter_lesson_options_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='datetime_end',
            field=models.DateTimeField(verbose_name='Длительность'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='datetime_start',
            field=models.DateTimeField(verbose_name='Начало занятия'),
        ),
    ]
