# Generated by Django 5.0.4 on 2025-02-22 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schooling', '0008_remove_lesson_homework_url_lesson_homework_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeworkfile',
            options={'verbose_name': 'файл', 'verbose_name_plural': 'файлы'},
        ),
        migrations.AlterModelOptions(
            name='homeworkimage',
            options={'verbose_name': 'изображение', 'verbose_name_plural': 'изображения'},
        ),
    ]
