# Generated by Django 5.0.6 on 2024-06-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooling', '0008_alter_lesson_datetime_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='datetime_end',
            field=models.DateTimeField(verbose_name='Время окончания занятия'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='datetime_start',
            field=models.DateTimeField(verbose_name='Время начала занятия'),
        ),
    ]
