# Generated by Django 5.0.7 on 2024-08-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooling', '0008_lesson_is_passed_student_lesson_is_passed_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='is_passed_student',
            field=models.BooleanField(default=False, verbose_name='Занятие подтверждено учеником'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='is_passed_teacher',
            field=models.BooleanField(default=False, verbose_name='Занятие подтверждено учителем'),
        ),
    ]
