# Generated by Django 5.0.4 on 2025-02-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooling', '0008_lesson_homework_text_homeworkfile_homeworkimage'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lesson',
            name='unique_lesson',
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('subject', 'teacher_id', 'student_id', 'datetime_start', 'duration'), name='unique_lesson'),
        ),
    ]
