# Generated by Django 5.0.7 on 2024-07-31 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schooling', '0009_alter_student_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('name', 'datetime_start')},
        ),
    ]
