# Generated by Django 5.0.4 on 2025-03-01 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooling', '0009_remove_lesson_unique_lesson_lesson_unique_lesson'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessongroup',
            options={'verbose_name': 'расписание', 'verbose_name_plural': 'Расписание'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['name', 'surname'], 'verbose_name': 'Ученик', 'verbose_name_plural': 'Ученики'},
        ),
        migrations.AlterField(
            model_name='lesson',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='schooling.lessongroup', verbose_name='Расписание'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='schooling.student', verbose_name='Ученик'),
        ),
        migrations.AlterField(
            model_name='lessongroup',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_groups', to='schooling.student', verbose_name='Ученик'),
        ),
    ]
