# Generated by Django 5.0.4 on 2025-03-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooling', '0010_alter_lessongroup_options_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_count',
            field=models.PositiveIntegerField(default=1, help_text='Указанное количество занятий будет создано с интервалом в 1 неделю.', verbose_name='Количество создаваемых занятий'),
        ),
    ]
