# Generated by Django 5.0.4 on 2026-05-29 12:59

import schooling.validators.file_size_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooling', '0011_alter_lesson_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='past_lessons',
            field=models.PositiveIntegerField(default=0, verbose_name='Прошедшие занятия'),
        ),
        migrations.AlterField(
            model_name='homeworkfile',
            name='file',
            field=models.FileField(upload_to='lesson_homework/files/', validators=[schooling.validators.file_size_validator.validate_file_size], verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='homeworkimage',
            name='image',
            field=models.ImageField(upload_to='lesson_homework/images/', validators=[schooling.validators.file_size_validator.validate_file_size], verbose_name='Изображение'),
        ),
    ]
