# Generated by Django 5.0.4 on 2026-08-12 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooling', '0012_student_past_lessons_alter_homeworkfile_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrialLessonRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, max_length=150, null=True, verbose_name='Username в Telegram')),
                ('full_name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Имя пользователя')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('processed', 'Обработана')], default='new', max_length=20, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий менеджера')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата обработки')),
            ],
            options={
                'verbose_name': 'заявка на пробный урок',
                'verbose_name_plural': 'Заявки на пробный урок',
                'ordering': ['-created_at'],
            },
        ),
    ]
