# Generated by Django 5.0.4 on 2026-09-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooling', '0013_triallessonrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrialLessonBroadcastMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='Летние каникулы близятся к концу, скоро начнется учебный год 📚 Команда преподавателей Goodstart уже трудится во всю и проводит уроки 🥰\n\nНаши лучшие репетиторы проводят пробные занятия и забивают свое расписание на учебное время! Чтобы не опоздать к хорошему преподавателю, рекомендуем заранее записаться, пройти бесплатный урок и зафиксировать свое расписание, оплатив удобный формат занятий 📅\n\nЗаписаться на пробный урок 👇', help_text='Поддерживается: **жирный**, *курсив*, `код`, [текст ссылки](https://...). Перед отправкой в Telegram текст автоматически конвертируется в MarkdownV2 с экранированием спецсимволов.', verbose_name='Текст сообщения (Markdown)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'текст рассылки пробного урока',
                'verbose_name_plural': 'Текст рассылки пробного урока',
            },
        ),
        migrations.AlterField(
            model_name='student',
            name='state',
            field=models.CharField(choices=[('start', 'Start'), ('help', 'Help'), ('schedule', 'Schedule'), ('feedback', 'Feedback'), ('feedback_subject_msg', 'Feedback Subject'), ('feedback_body_msg', 'Feedback Body'), ('left_lessons', 'Left Lessons'), ('write_teacher', 'Write Teacher'), ('write_teacher_message', 'Write Teacher Message')], default='start', max_length=50, verbose_name='Состояние пользователя'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='state',
            field=models.CharField(choices=[('start', 'Start'), ('help', 'Help'), ('schedule', 'Schedule'), ('feedback', 'Feedback'), ('feedback_subject_msg', 'Feedback Subject'), ('feedback_body_msg', 'Feedback Body'), ('left_lessons', 'Left Lessons'), ('write_teacher', 'Write Teacher'), ('write_teacher_message', 'Write Teacher Message')], default='start', max_length=50, verbose_name='Состояние пользователя'),
        ),
    ]
