# Generated by Django 5.0.4 on 2026-09-05 09:57

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schooling', '0014_triallessonbroadcastmessage_alter_student_state_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='triallessonbroadcastmessage',
            options={'verbose_name': 'текст рассылки', 'verbose_name_plural': 'Текст рассылки'},
        ),
        migrations.AlterModelOptions(
            name='triallessonrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'заявка из рассылки', 'verbose_name_plural': 'Заявки из рассылки'},
        ),
        migrations.AddField(
            model_name='triallessonrequest',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='RU', verbose_name='Номер телефона'),
        ),
    ]
