# Generated by Django 5.0.4 on 2026-09-05 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooling', '0015_alter_triallessonbroadcastmessage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='state',
            field=models.CharField(choices=[('start', 'Start'), ('help', 'Help'), ('schedule', 'Schedule'), ('feedback', 'Feedback'), ('feedback_subject_msg', 'Feedback Subject'), ('feedback_body_msg', 'Feedback Body'), ('left_lessons', 'Left Lessons'), ('write_teacher', 'Write Teacher'), ('write_teacher_message', 'Write Teacher Message'), ('write_student', 'Write Student'), ('write_student_message', 'Write Student Message')], default='start', max_length=50, verbose_name='Состояние пользователя'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='state',
            field=models.CharField(choices=[('start', 'Start'), ('help', 'Help'), ('schedule', 'Schedule'), ('feedback', 'Feedback'), ('feedback_subject_msg', 'Feedback Subject'), ('feedback_body_msg', 'Feedback Body'), ('left_lessons', 'Left Lessons'), ('write_teacher', 'Write Teacher'), ('write_teacher_message', 'Write Teacher Message'), ('write_student', 'Write Student'), ('write_student_message', 'Write Student Message')], default='start', max_length=50, verbose_name='Состояние пользователя'),
        ),
        migrations.CreateModel(
            name='TeacherStudentConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.TextField(blank=True, default='', verbose_name='Переписка')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Последнее сообщение')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='schooling.student', verbose_name='Ученик')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='schooling.teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'переписка преподавателя и ученика',
                'verbose_name_plural': 'Переписки преподавателей и учеников',
                'ordering': ['-updated_at'],
                'unique_together': {('teacher', 'student')},
            },
        ),
    ]
