
volumes:
  pg_data:
  static:

services:
  db:
    image: postgres:latest
    env_file: ../../.env
    container_name: GoodStart-DB
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ../../src/
    env_file: ../../.env
    container_name: GoodStart-Backend
    depends_on:
      - db
    volumes:
      - static:/static


  gateway:
    build: ../nginx/
    container_name: GoodStart-Gateway
    volumes:
      - ../../static:/static/
    ports:
      - 8000:80
