# Generated by Django 5.0.6 on 2024-06-14 16:29

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schooling', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.PositiveBigIntegerField(help_text='Введите свой ID', unique=True, verbose_name='Telegram ID')),
                ('role', models.CharField(choices=[('teacher', 'Преподаватель'), ('student', 'Учащийся')], max_length=20, verbose_name='Роль')),
                ('name', models.CharField(help_text='Обязательное поле', max_length=20, verbose_name='Имя')),
                ('surname', models.CharField(help_text='Обязательное поле', max_length=20, verbose_name='Фамилия')),
                ('city', models.CharField(max_length=20, verbose_name='Город')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(help_text='Формат +7XXXXXXXXXX', max_length=128, region=None, verbose_name='Номер телефона')),
                ('parents_contacts', models.CharField(blank=True, max_length=256, null=True, verbose_name='Контакты представителей')),
                ('approved', models.BooleanField(default=False, verbose_name='Принять заявку')),
                ('study_class_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='potential_user', to='schooling.studyclass', verbose_name='ID учебного класса')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
