# Generated by Django 5.0.6 on 2024-06-04 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potential_user', '0001_initial'),
        ('schooling', '0005_alter_studyclass_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationform',
            name='parents_contacts',
            field=models.CharField(max_length=256, null=True, verbose_name='Контакты представителей'),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='study_class_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='potential_user', to='schooling.studyclass', verbose_name='ID учебного класса'),
        ),
    ]
