# Generated by Django 5.0.7 on 2024-07-31 17:22

import phonenumber_field.modelfields
import schooling.validator
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('potential_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationform',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Формат +7XXXXXXXXXX', max_length=128, region=None, validators=[schooling.validator.validate_phone_number], verbose_name='Номер телефона'),
        ),
    ]
