# Generated by Django 5.0.6 on 2024-06-06 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potential_user', '0002_applicationform_parents_contacts_and_more'),
        ('schooling', '0005_alter_studyclass_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationform',
            name='parents_contacts',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Контакты представителей'),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='study_class_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='potential_user', to='schooling.studyclass', verbose_name='ID учебного класса'),
        ),
    ]
