# Generated by Django 5.0.4 on 2025-02-16 15:34

import phonenumber_field.modelfields
import schooling.validators.phone_validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('potential_user', '0002_alter_applicationform_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationform',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Формат +7XXXXXXXXXX', max_length=128, region='RU', validators=[schooling.validators.phone_validators.validate_phone_number], verbose_name='Номер телефона'),
        ),
    ]
