# Generated by Django 5.0.6 on 2024-06-11 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potential_user', '0003_alter_applicationform_parents_contacts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationform',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Принять заявку'),
        ),
    ]
