
version: '3'

volumes:
  pg_data:
  static_volume:

services:
  db:
    image: postgres:latest
    env_file: ../../.env
    container_name: GoodStart-DB
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    # build: .
    image: ghcr.io/studio-yandex-practicum/goodstart_telegram_bot:feature-id-116-deploy
    env_file: ../../.env
    depends_on:
      - db
    volumes:
      - static_volume:/app/static/
    ports:
      - 8002:8000
  gateway:
    build: ./infra/
    volumes:
      - static_volume:/static/
    ports:
      - 8001:80
    depends_on:
      - backend