name: Pull and run on server

on:
  workflow_run:
    workflows:
      - Build and push Docker image
    types:
      - completed

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Copy docker-compose.dev.yaml via ssh
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        source: "infra/dev/docker-compose.dev.yaml"
        target: "Goodstart_telegram_bot"
    - name: Copy Dockerfile via ssh
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        source: "infra/Dockerfile"
        target: "Goodstart_telegram_bot"
    - name: Copy nginx.conf via ssh
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        source: "infra/nginx.conf"
        target: "Goodstart_telegram_bot"
    - name: Executing remote ssh commands to deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        timeout: 120s
        script: |
          cd Goodstart_telegram_bot/infra/dev
          # Выполняет pull образов с Docker Hub
          sudo docker compose -f docker-compose.dev.yaml pull
          # Перезапускает все контейнеры в Docker Compose
          sudo docker compose -f docker-compose.dev.yaml down
          sudo docker compose -f docker-compose.dev.yaml up -d
          # Выполняет удаление старых образов
          sudo docker image prune -f